[platformio]
default_envs = nucleo_g474re

[env]
build_flags =
  -Wall
  -Wextra
  -Werror

[env:nucleo_g474re]
platform = ststm32@19.7.0
board = nucleo_g474re
framework = arduino
monitor_speed = 115200
upload_protocol = stlink

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter =
  +<oomwoo_protocol.c>
  +<oomwoo_messages.c>
  +<oomwoo_cpu_ingress.c>
build_flags =
  ${env.build_flags}
  -DOOMWOO_PROTOCOL_EXPECTED_VERSION=1

[env:nucleo_g474re_v2]
extends = env:nucleo_g474re
build_flags =
  ${env.build_flags}
  -DOOMWOO_PROTOCOL_VERSION=2

[env:native_v2]
extends = env:native
build_flags =
  ${env.build_flags}
  -DOOMWOO_PROTOCOL_VERSION=2
  -DOOMWOO_PROTOCOL_EXPECTED_VERSION=2
